### ISSUE TITLE
How do we enable pre-fixing?

### ISSUE THREAD

**Issue by pretty** [bubobox/paint#27]
I see the opt param isn't enabled yet so we can enable pre-fixing, is there a way to manually enable in our own build?

**Comment by JorgenEvens** [comment]
Could you give us some more information on what it is you are trying to accomplish exactly?

You can set several options using the `opt` query parameter, which is [passed through](https://github.com/ambassify/paint/blob/master/src/helpers/sass.js#L81) all the way to `node-sass`' render method. But I'm not sure if that is what you are looking for or not.
